module.exports = {
  content: ['404.html', '_src-lp/blocks/**/*.js', '_src-lp/scripts/*.js'], // Files to analyze for used CSS classes
  css: ['node_modules/bootstrap/dist/css/bootstrap.min.css'], // CSS files to include
  defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
  safelist: [
    'carousel',
    'carousel-inner',
    'carousel-dark',
    'carousel-fade',
    'carousel-item-next',
    'carousel-item-start',
    'carousel-item-end',
    'carousel-item-prev',
    'carousel-control-prev',
    'carousel-control-next',
    'carousel-control-start',
    'carousel-control-end',
    'carousel-control-next-icon',
    'carousel-control-prev-icon',
    'pointer-event',
    'justify-content-end',
    'p-5', 'pt-3', 'my-5', 'my-0', 'my-1', 'my-2', 'mx-auto',
    'table-bordered',
    'col-lg-8', 'col-lg-4', 'col-lg-9', 'col-lg-3', 'g-0', 'row',
    'col-12', 'd-flex', 'flex-column', 'justify-content-start',
    'col-md-5', 'col-md-2', 'col-md-1', 'col-md-6', 'col-xl-5', 'col-xl-1', 'col-xl-6',
    'align-items-center', 'g-3', 'btn', 'btn-danger', 'btn-outline-primary',
    'w-100', 'mb-2', 'text-center', 'fw-medium', 'text-muted', 'd-block', 'justify-content-center',
  ],
  blocklist: ['strong'],
};
