name: Accept Baselines Workflow

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Conditions
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR is already merged. Exiting."
            exit 1
          fi

          if [[ ! "${{ github.event.label.name }}" == "accept-baselines" ]]; then
            echo "Label 'accept-baselines' not found. Exiting."
            exit 1
          fi
      - name: Verify Required Checks
        run: |
          CHECKS=$(gh pr checks ${{ github.event.pull_request.number }} --json checks --jq '.checks[].status')
          if [[ "$CHECKS" =~ "failure" ]]; then
            echo "Some required checks failed. Exiting."
            exit 1
          fi

      - name: Verify Approvals
        run: |
          APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[] | select(.state=="APPROVED")] | length')
          if [[ "$APPROVALS" -lt 2 ]]; then
            echo "Not enough approvals. Exiting."
            exit 1
          fi

  acquire-lock:
    needs: check-conditions
    runs-on: ubuntu-latest
    steps:
      - name: Check for Lock
        id: check-lock
        run: |
          LOCK_FILE_URL="https://github.com/bitdefender/www-landing-pages/blob/gi-flow/.baseline-lock"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $LOCK_FILE_URL)
          if [ "$STATUS_CODE" == "200" ]; then
            echo "Baseline update is already in progress. Exiting."
            exit 1
          fi
      - name: Acquire Lock
        run: |
          echo "Updating baselines for PR #${{ github.event.pull_request.number }}" > .baseline-lock
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout main
          git pull origin main
          git add .baseline-lock
          git commit -m "Lock for baseline update by PR #${{ github.event.pull_request.number }}"
          git push origin main

  update-baselines:
    needs: acquire-lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Baselines in Ghost Inspector
        run: npm run test:accept-baseline
        env:
          GI_KEY: ${{ secrets.GI_KEY }}

      - name: Release Lock
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout main
          git pull origin main
          git rm .baseline-lock
          git commit -m "Release lock for baseline update"
          git push origin main

  auto-merge:
    needs: update-baselines
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge PR
        if: success()
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
