name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  compile-sass:
    runs-on: ubuntu-latest
    steps:
      - run: npm run compile-sass
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
