name: Run Tests and Snapshots

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Accept Baselines Workflow"]
    types:
      - completed

jobs:
  setup-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4'
      - run: npm install

  lint:
    needs: setup-nodejs
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint

  unit-tests:
    needs: setup-nodejs
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test:unit

  snapshots-tests:
    needs: [lint, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Get Branch Name
        id: extract_branch_name
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Run Snapshot Tests
        run: npm run test:snapshots
        env:
          GI_KEY: ${{ secrets.GI_KEY }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: Inform Developer About Snapshot Failures
        if: failure()
        run: echo "Snapshots failed. Add the 'accept-baselines' label to update the baselines or fix your code."

      - name: Set PR Ready for Merge
        if: success()
        run: echo "PR is ready for merge."
