name: Workflow

on: [pull_request]

jobs:
  setup-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4'
      - run: npm install

  lint:
    needs: setup-nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint

  unit-tests:
    needs: setup-nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test:unit

  snapshots-tests:
    needs: setup-nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      # Dynamically extract the branch name from GITHUB_REF
      - name: Get Branch Name
        id: extract_branch_name
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - run: npm run test:snapshots
        env:
          GI_KEY: ${{ secrets.GI_KEY }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
      - run: npm run compile-sass
        env:
          CI: true

      - name: Save Accept Baseline Option
        if: github.event.inputs.accept_new_baseline == 'true'
        run: echo "accept_new_baseline=true" > accept_baseline_flag
      - name: Upload Baseline Acceptance Artifact
        uses: actions/upload-artifact@v3
        with:
          name: baseline-acceptance
          path: accept_baseline_flag

  accept-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Baseline Acceptance Artifact
        uses: actions/download-artifact@v3
        with:
          name: baseline-acceptance

      - name: Check Baseline Acceptance Flag
        id: check_accept
        run: |
          if [[ -f "accept_baseline_flag" ]]; then
            echo "accept_baseline=true" >> $GITHUB_ENV
          else
            echo "accept_baseline=false" >> $GITHUB_ENV
          fi

      - name: Update Baseline in Ghost Inspector
        if: env.accept_baseline == 'true'
        run: |
          # Call Ghost Inspector API to update the baseline
          # Example curl command:
          curl -X POST "https://api.ghostinspector.com/v1/tests/update-baseline?apiKey=${{ secrets.GI_KEY }}"
