name: Update PR Description Test URLs
on:
  pull_request_target:
    types:
      - opened

jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        run: |
          PR_UPDATED_BODY="$(
            gh api /repos/$OWNER/$REPO/pulls/$PR_NUMBER | jq -r '.body' | sed 's/<branch>/${{github.ref_name}}/g'
          )"
          gh api --method PATCH /repos/$OWNER/$REPO/pulls/$PR_NUMBER -f body="$PR_UPDATED_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.number }}
